## ReferenceError: You are trying to import a file after the Jest environment has been torn down.

Unit Test Code를 시도하던 중, 발생했다.

UsersModule을 불러올 것이 아니라, AppModule을 불러오는 것으로 해결했다.

### 이전코드

```
beforeEach(async () => {
    const moduleRef: TestingModule = await Test.createTestingModule({
      imports: [UsersModule],
    }).compile();

    app = moduleRef.createNestApplication();
    await app.init();

    usersService = moduleRef.get<UsersService>(UsersService);
  });
```

### 변경코드

```
beforeEach(async () => {
    const moduleRef: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleRef.createNestApplication();
    await app.init();

    usersService = moduleRef.get<UsersService>(UsersService);
  });
```
아마도 AppModule을 Import할 때 env를 받아오는 것으로 시작해야하는데
UsersModule을 Import해서 env를 받아오지 못해서 생긴 문제로 생각된다.

## Nest can't resolve dependencies of the UsersService (?, DataSource, ConfigService, JwtService). Please make sure that the argument UserRepository at index [0] is available in the RootTestModule context

앱을 먼저 생성한다음 usersService에 UsersService 객체를 담아야 하는데, 객체먼저 받아오려고 해서
종속성의 논리에따라 AppModule => UsersModule => UsersController => UsersService => UsersRepository 순서대로
생성이 되지 않았는데 불러오려고 해서 발생한 문제였다.

### 이전코드

```
usersService = moduleRef.get<UsersService>(UsersService);
app = moduleRef.createNestApplication();
    await app.init();
```

### 변경코드
```
app = moduleRef.createNestApplication();
    await app.init();

usersService = moduleRef.get<UsersService>(UsersService);
```

## 파멸적인 문제점, Transaction Interceptor를 사용하면 TestCode쓰기 어렵다.

아주아주 힘듭니다..